
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `stockControl` DEFAULT CHARACTER SET utf8 ;
USE `stockControl` ;

CREATE TABLE IF NOT EXISTS `stockControl`.`prod_product` (
  `prod_id` INT NOT NULL AUTO_INCREMENT,
  `prod_quantity` INT NOT NULL,
  `prod_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`prod_id`),
  UNIQUE INDEX `prod_id_UNIQUE` (`prod_id` ASC) VISIBLE)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;